# Generated by Django 2.1.5 on 2021-08-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddance', '0002_auto_20210804_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
