# Generated by Django 2.1.5 on 2021-08-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddance', '0008_confirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
